language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
script: 'npm run coverage'
before_install:
  - sudo apt-get install libpcap-dev
after_success:
  - 'npm run coveralls'
  - 'npm run codecov'
