version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo
    dependencies:
      pre:
        - sudo apt-get update; sudo apt-get install libpcap-dev
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test


